Extend hooks

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,5 +1,18 @@
 #!/bin/sh
 
+cargo build 1>/dev/null 2>/dev/null
+if [[ $? -ne 0 ]]; then
+    echo "cargo build failed; fix it before committing"
+    exit 1
+fi
+
+export RUSTFLAGS="-D warnings"
+cargo build 1>/dev/null 2>/dev/null
+if [[ $? -ne 0 ]]; then
+    echo "cargo lint check failed; resolve before committing"
+    exit 1
+fi
+
 cargo test 1>/dev/null 2>/dev/null
 if [[ $? -ne 0 ]]; then
     echo "cargo test found problems; resolve them before committing"
